"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {supabase} from "@/lib/supabase";
import {dreams} from "@/lib/themes";
type R={id:string;slug:string;parent_names:string;baby_name:string|null;due_date:string|null;baby_gender:string;theme:string;dream:string;welcome_message:string|null};
export default function Dashboard(){
 const[r,setR]=useState<R|null>(null);const[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=supabase();const{data:{user}}=await s.auth.getUser();if(!user){location.href="/login";return}const{data}=await s.from("registries").select("*").eq("owner_id",user.id).limit(1).maybeSingle();if(data)setR(data);setLoading(false)})()},[]);
 async function create(){const s=supabase();const{data:{user}}=await s.auth.getUser();if(!user)return;const slug="little-"+crypto.randomUUID().slice(0,8);const{data}=await s.from("registries").insert({owner_id:user.id,slug,parent_names:"Our family",theme:"neutral",baby_gender:"neutral",dream:"explorer"}).select().single();setR(data)}
 async function save(){if(!r)return;const s=supabase();await s.from("registries").update({parent_names:r.parent_names,baby_name:r.baby_name,due_date:r.due_date,baby_gender:r.baby_gender,theme:r.theme,dream:r.dream,welcome_message:r.welcome_message}).eq("id",r.id);alert("Registry saved.")}
 if(loading)return <main className="center">Loading…</main>;
 if(!r)return <main className="center"><div className="panel"><h1>Your little registry</h1><p>Belum ada registry. Buat satu untuk mulai.</p><button onClick={create}>Buat registry</button></div></main>;
 return <main className={"dash theme-"+r.theme}><header><div><p className="eyebrow">PARENT VIEW</p><h1>{r.baby_name||"Your little one"}&apos;s registry</h1></div><Link className="ghost" href={"/r/"+r.slug}>Preview guest ↗</Link></header><div className="dashgrid"><section className="panel form"><h2>Baby & family</h2><label>Family / parent name<input value={r.parent_names} onChange={e=>setR({...r,parent_names:e.target.value})}/></label><label>Baby name<input value={r.baby_name||""} onChange={e=>setR({...r,baby_name:e.target.value})}/></label><label>Due / birth date<input type="date" value={r.due_date||""} onChange={e=>setR({...r,due_date:e.target.value})}/></label><label>Gender<select value={r.baby_gender} onChange={e=>setR({...r,baby_gender:e.target.value})}><option value="neutral">Neutral</option><option value="girl">Girl</option><option value="boy">Boy</option></select></label><label>Visual theme<select value={r.theme} onChange={e=>setR({...r,theme:e.target.value})}><option value="neutral">Little Meadow</option><option value="girl">Peach Garden</option><option value="boy">Sky Adventure</option></select></label><label>A little dream<select value={r.dream} onChange={e=>setR({...r,dream:e.target.value})}>{dreams.map(x=><option key={x}>{x}</option>)}</select></label><label>Guest message<textarea value={r.welcome_message||""} onChange={e=>setR({...r,welcome_message:e.target.value})}/></label><button onClick={save}>Save profile</button></section><ItemEditor registryId={r.id}/></div></main>
}
function ItemEditor({registryId}:{registryId:string}){const[items,setItems]=useState<any[]>([]);const[name,setName]=useState("");const[price,setPrice]=useState("");async function load(){const s=supabase();const{data}=await s.from("registry_items").select("*").eq("registry_id",registryId).order("created_at");setItems(data||[])}useEffect(()=>{load()},[registryId]);async function add(){if(!name.trim())return;const s=supabase();await s.from("registry_items").insert({registry_id:registryId,name,price:price?Number(price):null,category:"Essentials"});setName("");setPrice("");load()}async function toggle(x:any){const s=supabase();await s.from("registry_items").update({is_enabled:!x.is_enabled}).eq("id",x.id);load()}return <section className="panel"><h2>Registry items</h2><div className="addrow"><input placeholder="Add an item" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Price" inputMode="numeric" value={price} onChange={e=>setPrice(e.target.value)}/><button onClick={add}>Add</button></div><div className="itemlist">{items.map(x=><div className={"edititem "+(!x.is_enabled?"off":"")} key={x.id}><div><b>{x.name}</b><small>{x.price?new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(x.price):"No price yet"}</small></div><button className="ghost" onClick={()=>toggle(x)}>{x.is_enabled?"Hide":"Show"}</button></div>)}</div></section>}